Repository rwjblue/codemod-cli, pull requests merged in 2020-08, with the labels that each got.

#89 Added support for accepting `jscodeshift` ignore options (e.g. `--ignore-config` and `--ignore-pattern`)
  src/bin-support.js
  src/options-support.js
  tests/cli-test.js
Labels: enhancement

#90 Update automated release steps
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#91 Drop support for Node 13
  .github/workflows/ci.yml
  package.json
Labels: breaking
