Repository rwjblue/codemod-cli, pull requests merged in 2022-01, with the labels that each got.

#200 Drop Node 10 and 15 support.
  .github/workflows/ci.yml
  package.json
Labels: breaking

#168 fix: supply file list to jscodeshift via stdin
  src/bin-support.js
Labels: bug

#201 Migrate back to npm
  .github/workflows/ci.yml
  README.md
  RELEASE.md
  commands/global/new.js
  commands/local/generate/codemod.js
  commands/local/update-docs.js
  package-lock.json
  src/bin-support.js
  tests/cli-test.js
  yarn.lock
Labels: enhancement

#212 Update dependencies/devDependencies to latest
  package-lock.json
  package.json
Labels: internal
